FROM golang:1.23

# Installer les dépendances nécessaires pour X11
RUN apt-get update && apt-get install -y \
    libx11-dev \
    libxext-dev \
    libxtst-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxi-dev

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier go.mod et go.sum (si présents)
COPY go.mod go.sum ./

# Télécharger les dépendances
RUN go mod download

# Copier le reste du code source
COPY . .

# Construire l'application
RUN go build -o mousemover .

# Définir la commande par défaut pour exécuter l'application
CMD ["./mousemover"]